Global("localization", nil)

Global("Locales", {
	["rus"] = { 
	["Available"] = "В наличии",
	["Not available"] = "Отсутствует",
	["Inside: "] = "Внутри: ",
	["Pets"] = "Питомцы",
	["Rare Pets"] = "Диковинные питомцы",
	["Prophetic Card"] = "Карты Судьбы",
	["Unique Costumes"] = "Уникальные наряды",
	--costumes
	["Svyatogor's Bag"] = "Котомка Святогора",
	["Svyatogor's Cuirass"] = "Панцирь Святогора",
	["Backpack of the Inspired Inventor"] = "Сумка гениального изобретателя",
	["Costume of the Inspired Inventor"] = "Костюм гениального изобретателя",
	["Kit of the Dragonfighter"] = "Набор Драконоборца",
	["Mirror of the Dragonfighter"] = "Зерцало драконоборца",
	["Leaf Bag"] = "Сшитая из листвы сумка",
	["Forest Armor"] = "Лесная броня",
	["Cat in a Bag"] = "Кот в мешке",
	["Catologist's Outfit"] = "Одеяние котоведа",
	["Royal Set"] = "Королевский набор",
	["Royal Outfit"] = "Королевский костюм",
	["Old Travel Bag"] = "Старая дорожная сумка", 
	["Chestguard of the Sandstorm"] = "Панцирь песчаной бури",
	["Gravedigger's Bag"] = "Торба могильщика", 
	["Grim Reaper's Armor"] = "Доспех мрачного жнеца",
	["Chitin Box"] = "Хитиновая коробка", 
	["Chitin Chest"] = "Хитиновый доспех",
	["Rambling Storyteller's Bag"] = "Котомка бродячего сказочника", 
	["Storyteller's Jacket"] = "Куртка сказочника",
	["Embroidered Bag"] = "Расшитая котомка", 
	["Tunic of the Sly Fox"] = "Бушлат Хитрого Лиса",
	["Essedarius’ Bag"] = "Котомка эсседария",
	["Combat Armor of the Essedarius"] = "Боевой доспех эсседария",
	["Dog Trainer's Kit"] = "Набор кинолога",
	["Dog Trainer's Suit"] = "Униформа кинолога",
	["Beach Wear"] = "Пляжный набор",
	["Beach Wear Outfit"] = "Пляжный костюм",
	["Case of the Investigator"] = "Кейс испытателя",
	["Protective Costume of the Investigator"] = "Защитный костюм испытателя",
	["Dragon Rider's Equipment"] = "Вооружение драконьего всадника",
	["Dragon Rider's Shell"] = "Панцирь драконьего всадника",
	['Astral Treasures Outfit'] = 'Набор "Сокровища астрала"',
	["Costume of the Astral Catcher"] = "Костюм астрального ловчего",
	["Mana Guard Uniform"] = "Униформа мана-гвардейца",
	["Mana Guard’s Breastplate"] = "Нагрудник мана-гвардейца",
	["Filibuster's Treasure"] = "Клад флибустьера",
	["Filibuster’s Jacket"] = "Камзол флибустьера",
	["Bag of the Doomsday Horseman"] = "Сумка всадника апокалипсиса",
	["Costume of the Last Hour"] = "Камзол последнего часа",
	["Chest of the Fallen Templar"] = "Ларчик Падшего Храмовника",
	["Heretic's Golden Armor"] = "Златой доспех Нечестивца",
	["Hero Constellation"] = "Созвездие Героя",
	["Armor of the Distant Stars"] = "Доспех далёких звёзд",
	--not found in eng_eu client
	["Imperial Thunder Robes"] = "Одеяния грома Империи",
	["Thunder Breastplate of the Empire"] = "Кираса грома Империи",
	--holyweapons
	['Weapon Appearance "Good Intentions"'] = 'Обличье оружия "Благие помыслы"',
	['Weapon Appearance "True Faith"'] = 'Обличье оружия "Чистая вера"',
	['Weapon Appearance "Unavoidable Punishment"'] = 'Обличье оружия "Неотвратимая кара"',
	['Weapon Appearance "Mysterious Twilight"'] = 'Обличье оружия "Таинственные сумерки"',
	['Weapon Appearance "Imminent Demise"'] = 'Обличье оружия "Неумолимая погибель"',
	['Weapon Appearance "Dazzling Dawn"'] = 'Обличье оружия "Ослепительная заря"',
	['Weapon Appearance "Wrath of Gods"'] = 'Обличье оружия "Гнев богов"',
	['Weapon Appearance "Frozen Pride"'] = 'Обличье оружия "Ледяная гордыня"',
	['Weapon Appearance "Greedy Eye'] = 'Обличье оружия "Алчный взор"',
	['Weapon Appearance "Black Envy"'] = 'Обличье оружия "Черная зависть"',
	['Weapon Appearance "Great Grief"'] = 'Обличье оружия "Великая скорбь"',
	['Weapon Appearance "Ardent Fervor"'] = 'Обличье оружия "Пылкая страсть"',
	['Weapon Appearance "Whisper of the Dead"'] = 'Обличье оружия "Шёпот мёртвых"',
	['Weapon Appearance "Madness"'] = 'Обличье оружия "Безумие"',
	['Weapon Appearance "Ancient Legends"'] = 'Обличье оружия "Седые легенды"',
	['Weapon Appearance "Deadly Beauty"'] = 'Обличье оружия "Гибельная красота"',
	['Weapon Appearance "Valor and Honor"'] = 'Обличье оружия "Отвага и честь"',
	['Weapon Appearance "Civil Duty"'] = 'Обличье оружия "Долг Родине"',
--	[[Weapon Appearance' "Ancestors Guidance"]] = 'Обличье оружия "Заветы предков"',
	['Weapon Appearance "Ancestors Guidance"'] = 'Обличье оружия "Заветы предков"',
	['Weapon Appearance "Harmony"'] = 'Обличье оружия "Гармония"',
	['Weapon Appearance "Madness of War"'] = 'Обличье оружия "Безумие войны"',
	['Weapon Appearance "Winter Dusk"'] = 'Обличье оружия "Зимний закат"',
	['Weapon Appearance "White Night"'] = 'Обличье оружия "Белая ночь"',
	['Weapon Appearance "Pole Star"'] = 'Обличье оружия "Полярная звезда"',
	['Weapon Appearance "Eternal Winter"'] = 'Обличье оружия "Вечная зима"',
	['Weapon Appearance "Astral Nightmare"'] = 'Обличье оружия «Астральный кошмар»',
	['Weapon Appearance "Restless Illusions"'] = 'Обличье оружия «Беспокойные наваждения»',
	['Weapon Appearance "Dormant Horror"'] = 'Обличье оружия «Спящий ужас»',
	['Weapon Appearance "Crimson Dawn"'] = 'Обличье оружия «Багровый закат»',
	['Weapon Appearance "Rising Sun"'] = 'Обличье оружия «Утренняя заря»',
	['Weapon Appearance "Azure Sky"'] = 'Обличье оружия «Лазурное небо»',
	['Weapon Appearance "Bloody Crusader"'] = 'Обличье оружия «Кровавый витязь»',
	['Weapon Appearance "Lunar Crusader"'] = 'Обличье оружия «Лунный витязь»',
	['Weapon Appearance "Solar Crusader"'] = 'Обличье оружия «Солнечный витязь»',
	['Weapon Appearance "Spiritual Flame"'] = 'Обличье оружия «Пламя духов»',
	['Weapon Appearance "Clear Perspective"'] = 'Обличье оружия «Ясный взгляд»',
	['Weapon Appearance "Impenetrable Darkness"'] = 'Обличье оружия «Непроглядная тьма»',
	
	['Holy Weapon of Bliss'] = 'Святое оружие Благости',
	['Holy Weapon of Judgement'] = 'Святое оружие Кары',
	['Holy Weapon of Faith'] = 'Святое оружие Веры',
	['Holy Weapon of Twilight'] = 'Святое оружие Сумерек',
	['Holy Weapon of Demise'] = 'Святое оружие Погибели',
	['Holy Weapon of Dawn'] = 'Святое оружие Зари',
	['Holy Weapon of Wrath'] = 'Святое оружие Гнева',
	['Holy Weapon of Pride'] = 'Святое оружие Гордыни',
	['Holy Weapon of Greed'] = 'Святое оружие Алчности',
	['Holy Weapon of Grudge'] = 'Святое оружие Зависти',
	['Holy Weapon of Grief'] = 'Святое оружие Скорби',
	['Holy Weapon of Fervor'] = 'Святое оружие Страсти',
	['Holy Weapon from the Dead City'] = 'Святое оружие из Мёртвого города',
	['Holy Weapon from Teps Pyramid'] = 'Святое оружие из Пирамиды Тэпа',
	['Holy Weapon of Eclipse'] = 'Святое оружие Затмения',
	['Holy Weapon of Beauty'] = 'Святое оружие Красоты',
	['Holy Weapon of Courage'] = 'Святое оружие Отваги',
	['Holy Weapon of Duty'] = 'Святое оружие Долга',
	['Holy Weapon of the Ancestors'] = 'Святое оружие Предков',
	['Holy Weapon of Harmony'] = 'Святое оружие Гармонии',
	['Holy Weapon of War'] = 'Святое оружие Войны',
	['Holy Weapon of Dusk'] = 'Святое оружие Заката',
	['Holy Weapon of White Night'] = 'Святое оружие Белой ночи',
	['Holy Weapons of Pole Star'] = 'Святое оружие Полярной звезды',
	['Holy Weapons of Eternal Winter'] = 'Святое оружие Вечной зимы',
	['Holy Weapon of Nightmares'] = 'Святое оружие Кошмаров',
	['Holy Weapon of Illusions'] = 'Святое оружие Наваждений',
	['Holy Weapon of Horror'] = 'Святое оружие Ужаса',
	['Holy Weapon of Crimson Dawn'] = 'Святое оружие Багрового заката',
	['Holy Weapon of Rising Sun'] = 'Святое оружие Утренней зари',
	['Holy Weapon of Azure Sky'] = 'Святое оружие Лазурного неба',
	['Holy Weapon of the Bloody Crusader'] = 'Святое оружие Кровавого Витязя',
	['Holy Weapon of the Lunar Crusader'] = 'Святое оружие Лунного Витязя',
	['Holy Weapon of the Solar Crusader'] = 'Святое оружие Солнечного Витязя',
	['Holy Weapon of the Spiritual Flame'] = 'Святое оружие Пламени духов',
	['Holy Weapon of the Clear Perspective'] = 'Святое оружие Ясного взгляда',
	['Holy Weapon of the Pitch Darkness'] = 'Святое оружие Непроглядной тьмы',
	--not found in eng_eu client
	['Weapon Appearance "The Pyramids of the Dead"'] = 'Обличье оружия «Пирамиды мёртвых»',
	['Weapon Appearance "Heresy cult"'] = 'Обличье оружия «Ересь культа»',
	['Weapon Appearance "Power Sprout"'] = 'Обличье оружия «Сила Ростка»',
	
	['Holy Weapon of Pyramid'] = 'Святое оружие Пирамид',
	['Holy Weapon of Heresy'] = 'Святое оружие Ереси',
	['Holy Weapon of Sprout'] = 'Святое оружие Ростка',
	},
		
	["eng_eu"] = { 
	["Beach Wear Outfit"] = "Beach Wear",
	['Holy Weapon from Teps Pyramid'] = "Holy Weapon from".." Tep's ".."Pyramid",
	['Weapon Appearance "Ancestors Guidance"'] = "'Weapon Appearance' "..'"Ancestors Guidance"'
	}
})

localization = common.GetLocalization()
function GTL( strTextName )
	return Locales[ localization ][ strTextName ] or Locales[ "eng_eu" ][ strTextName ] or strTextName
end
